food/urls.py
from . import views
from django.urls import path

app_name='food'
urlpatterns = [
    #/food/
    path('', views.IndexClassView.as_view(), name='index'),
    path('item/', views.item, name='item'),
    #path('<int:item_id>/',views.detail,name="detail"),
    path('<int:pk>/',views.FoodDetail.as_view(),name="detail"),
    # add items
    path('add',views.CreateItem.as_view(),name='create_item'),
    #edit
    path('update/<int:id>/',views.update_item,name='update_item'),
    #delete
    path('delete/<int:id>/',views.delete_item,name='delete_item'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from users import views as user_views
from django.contrib.auth import views as authentication_views
from django.conf import settings
from food import views
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.home,name='home'),
    path('food/',include('food.urls')),
    path('register/',user_views.register,name='register'),
    path('login/',authentication_views.LoginView.as_view(template_name='users/login.html'),name='login'),
    path('logout/',authentication_views.LogoutView.as_view(template_name='food/home.html'),name='home1'),
    path('profile/',user_views.profilepage,name='profile'),
]


urlpatterns += [
    # ... the rest of your URLconf goes here ...
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

food/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

# Create your models here.



class Item(models.Model):

    def __str__(self):
        return self.item_name
    user_name=models.ForeignKey(User,on_delete = models.CASCADE,default=1)
    item_name=models.CharField(max_length=200)
    item_desc = models.CharField(max_length=200)
    item_price = models.IntegerField()
    item_image=models.CharField(max_length=500,default="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQrvX8szwybkA8_2wFG8BrFkHVcQJFaVA6H_g&s")

    def get_absolute_url(self):
        return reverse("food:detail",kwargs={"pk":self.pk})

users/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Profile(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    image = models.ImageField(default='profilepic.jpg',upload_to='profile_pictures')
    location = models.CharField(max_length=100)

    def __str__(self):
        return self.user.username


food/forms.py
from django import forms
from .models import Item

class ItemForm(forms.ModelForm):
    class Meta:
        model=Item
        fields=['item_name','item_desc','item_price','item_image']

users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class RegisterForm(UserCreationForm):
    email=forms.EmailField()

    class Meta:
        model=User
        fields=['username','email','password1','password2']

food/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from .models import Item
from django.template import loader
from .forms import ItemForm
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView



# Create your views here.
def index(request):
    item_list=Item.objects.all()
    #template=loader.get_template("food/index.html")
    context={
        "item_list":item_list,
    }
    #return HttpResponse(template.render(context,request))
    return render(request,"food/index.html",context)

class IndexClassView(ListView):
    model=Item
    template_name ='food/index.html'
    context_object_name = 'item_list'

def item(request):
    return HttpResponse("<h1>This is an item view</h1>")

def detail(request,item_id):
    item=Item.objects.get(pk=item_id)
    context={
        'item':item,
    }
    #return HttpResponse("This is item no./id : %s" % item_id)
    return render(request,"food/detail.html",context)

class FoodDetail(DetailView):
    model=Item
    template_name = 'food/detail.html'

def create_item(request):
    form=ItemForm(request.POST or None)

    if form.is_valid():
        form.save()
        return redirect('food:index')

    return render(request,'food/item-form.html',{'form':form})

#This is class based view for create item

class CreateItem(CreateView):
    model=Item
    fields=['item_name','item_desc','item_price','item_image']
    template_name='food/item-form.html'
    def form_valid(self,form):
        form.instance.user_name=self.request.user

        return super().form_valid(form)

def update_item(request,id):
    item=Item.objects.get(id=id)
    form=ItemForm(request.POST or None,instance=item)

    if form.is_valid():
        form.save()
        return redirect('food:index')

    return render(request,'food/item-form.html',{'form':form,'item':item})

def delete_item(request,id):
    item=Item.objects.get(id=id)

    if request.method == "POST":
        item.delete()
        return redirect('food:index')
    return render(request,'food/item-delete.html',{'item':item})

def home(request):
    return render(request,'food/home.html')



users/views.py
from django.shortcuts import render,redirect
from django.contrib import messages
from .forms import RegisterForm
from django.contrib.auth.decorators import login_required

# Create your views here.
def register(request):
    if request.method=="POST":
        form=RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username=form.cleaned_data.get('username')
            messages.success(request,f'Welcome {username}, your account is created')
            return redirect('login')
    #old code
    else:
        form=RegisterForm()

    return render(request,'users/register.html',{'form':form})

@login_required
def profilepage(request):
    return render(request,'users/profile.html')

food/templates/food/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
   <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'food/stiles.css' %}">
    <title>Document</title>
</head>
<nav class="navbar navbar-dark bg-dark">
    <a href="#" class="navbar-brand">FoodApp</a>
    <div class="navbar">

        {% if user.is_authenticated %}

        <a href="{% url 'profile' %}">Profile</a>
        <a class="nav-item nav-link" href="{% url 'food:index' %}">View Item</a>
        <a class="nav-item nav-link" href="{% url 'food:create_item' %}">Add Item</a>
        <a href="{% url 'home1' %}">Logout</a>
        {% else %}

        <a class="anchor" href="{% url 'register' %}" >Register</a>
        <a class="anchor" href="{% url 'login' %}" >Login</a>
        {% endif %}


    </div>

</nav>
{% if messages %}
{% for message in messages %}
<div class="alert alert-{{message.tags}}">{{ message }}</div>

{% endfor %}
{% endif %}

{% block body %}
{% endblock %}

</html>

food/templates/food/detail.html
{% extends 'food/base.html' %}

{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <img height="300px" src="{{item.item_image}}" class="card"/>

        </div>
        <div class="col-md-6">
            <h1>{{object.item_name}}</h1><br>
            <h5>{{object.item_desc}}</h5><br>
            <h5>${{object.item_price}}</h5>
            <a href="{% url 'food:delete_item' item.id %} " class="btn btn-danger">Delete</a>
            <a href="{% url 'food:update_item' item.id %}" class="btn btn-success">Edit</a>

        </div>
    </div>
</div>


{% endblock %}

food/templates/food/home.html
{% extends 'food/base.html' %}

{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-6 offset-md-3">
        <div class="card">
                <div class="card-header text-white bg-info">
                    <div class="card-title">
                        <h2 class="offset-md-1">Welcome to Food Menu App</h2></br>
                            <h6 class="offset-md-3">Good Food and Great Vibes<h6>

                    </div>
                </div><br><br>

        </div>
        </div>

        <div class="col-md-4 offset-md-4">
            <div class="card">
                <div class="card-header text-white bg-info">
                    <div class="card-title">

                        <b>Login or Sign Up</b>

                    </div>
                </div>
                <div class="card-body">
                    <h5>Please Register</h5>
                    <p>Already Registered? <a href="{% url 'login' %}">Login</a></p>


                    <a href="{% url 'register' %}" class="btn btn-primary">Register</a>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

food/templates/food/index.html

{% extends 'food/base.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Document</title>

</head>
<body >
{% block body %}
{% for item in item_list %}
<div class="row">
    <div class="col-md-3 offset-md-2">
        <img class="card" height="150px" src="{{item.item_image}}"/>

    </div>
    <div class="col-md-4">
        <h3>{{ item.item_name }}</h3>
        <h6>${{ item.item_price }}</h6>
        <h6>{{item.user_name}}</h6>

    </div>

    <div class="col-md-2">
        <a href="{% url 'food:detail' item.id %}" class="btn btn-success">Details</a>

    </div>

</div>



{% endfor %}
{% endblock%}


this is the old code

<ul>
    <li>
        <a href="">{{item.id}} -- {{item.item_name}}</a>
    </li>
</ul>



</body>
</html>

food/templates/food/item-delete.html

<form method="POST">
    {% csrf_token %}
    <h2>Are you sure you want to delete {{ item.item_name }}</h2>
    <button type="submit">Confirm</button>
</form>

food/templates/food/item-form.html
{% extends 'food/base.html' %}
{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-4 offset-md-4">
            <div class="card">
                <div class="card-header text-white bg-info">
                    <div class="card-title">
                        Add Item
                    </div>
                </div>
                <div class="card-body">
                    <form method="POST">
                        {% csrf_token %}
                        {% for field in form %}
                        <div class="form-group">
                            {{field.name}}
                            <br>
                            {{field}}
                        </div>
                        {% endfor %}
                        <button class="bg-info" type="submit">Save</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>


{% endblock %}

users/templates/users/login.html
{% extends 'food/base.html' %}

{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-4 offset-md-4">
            <div class="card">
                <div class="card-header text-white bg-info">
                    <div class="card-title">
                        Login
                    </div>
                </div>
                <div class="card-body">
                    <form method="POST">
                        {% csrf_token %}
                        {% for field in form %}
                        <div class="form-group">
                            {{field.name}}
                            {{field}}
                        </div>
                        {% endfor %}
                        <button class="btn-info" type="submit">Login</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}








users/templates/users/logout.html
{% extends 'food/base.html' %}
<h1>You have been logged out</h1>

users/templates/users/profile.html

<h1>{{ user.username }}</h1>
<img width="100 px" height="100 px" src ="{{ user.profile.image.url}}">


users/templates/users/register.html
{% extends 'food/base.html' %}

{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-4 offset-md-4">
            <div class="card">
                <div class="card-header text-white bg-info">
                    <div class="card-title">
                        Register
                    </div>
                </div>
                <div class="card-body">
                    <form method="POST">
                        {% csrf_token %}
                        {% for field in form %}
                        <div class="form-group">
                            {{ field.name }}
                            <br>
                            {{ field }}
                        </div>
                        {% endfor %}
                        <button class="btn-info" type="submit">Signup</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}






